/* eslint-disable */
// ETW — Indicator Migration Script
// Adds missing indicators, fixes wrong WB codes, adds polarity/displayUnit
// Safe to run multiple times (upsert by slug).

import { PrismaClient } from "@prisma/client";
import dotenv from "dotenv";
dotenv.config();

const prisma = new PrismaClient();

// Full indicator catalog — 39 indicators + 2 manual-only
// polarity: POSITIVE (high = better), NEGATIVE (high = worse), NEUTRAL
const INDICATORS = [
  // ── ECONOMY ──────────────────────────────────────────────────────────────
  {
    slug: "gdp-total",
    name: "GDP (Total)",
    category: "Economy",
    worldBankCode: "NY.GDP.MKTP.CD",
    imfCode: null,
    unit: "Current US$",
    displayUnit: "US$",
    polarity: "POSITIVE",
    polarityRationale: "Higher GDP indicates a larger total economy, though it does not reflect per-capita living standards.",
    definition: "Gross domestic product (GDP) is the monetary value of all finished goods and services produced within a country's borders in a specific time period. Measured in current US dollars.",
    methodology: "Sum of gross value added by all resident producers plus product taxes minus subsidies. World Bank uses official exchange rates.",
  },
  {
    slug: "gdp-per-capita",
    name: "GDP per Capita",
    category: "Economy",
    worldBankCode: "NY.GDP.PCAP.CD",
    imfCode: null,
    unit: "Current US$",
    displayUnit: "US$",
    polarity: "POSITIVE",
    polarityRationale: "Higher GDP per capita generally indicates greater average economic output per person.",
    definition: "Gross domestic product divided by midyear population. Measured in current US dollars. This is the most common cross-country income comparison metric.",
    methodology: "GDP at purchaser's prices divided by midyear population, converted to US dollars using official exchange rates.",
  },
  {
    slug: "gdp-per-capita-ppp",
    name: "GDP per Capita, PPP",
    category: "Economy",
    worldBankCode: "NY.GDP.PCAP.PP.CD",
    imfCode: null,
    unit: "Current international $",
    displayUnit: "Int'l $",
    polarity: "POSITIVE",
    polarityRationale: "PPP-adjusted GDP per capita accounts for price differences between countries, giving a better picture of actual purchasing power.",
    definition: "GDP per capita converted to international dollars using purchasing power parity (PPP) rates, which equalise purchasing power across countries.",
    methodology: "Derived from GDP in US dollars and PPP conversion factors from the World Bank's International Comparison Program.",
  },
  {
    slug: "gdp-growth",
    name: "GDP Growth (Annual %)",
    category: "Economy",
    worldBankCode: "NY.GDP.MKTP.KD.ZG",
    imfCode: "NGDP_RPCH",
    unit: "% per year",
    displayUnit: "%",
    polarity: "NEUTRAL",
    polarityRationale: "Growth is not inherently good or bad; very high growth may be unsustainable, while negative growth signals recession.",
    definition: "Annual percentage growth rate of GDP at market prices based on constant local currency. IMF WEO provides projections beyond the latest year.",
    methodology: "Constant price GDP change year-over-year. IMF figures may differ from WB due to different base years and revision cycles.",
  },
  {
    slug: "inflation-cpi",
    name: "Inflation (CPI Annual %)",
    category: "Economy",
    worldBankCode: "FP.CPI.TOTL.ZG",
    imfCode: "PCPIPCH",
    unit: "% per year",
    displayUnit: "%",
    polarity: "NEGATIVE",
    polarityRationale: "Very high inflation erodes purchasing power and economic stability. Moderate inflation (2–4%) is generally considered acceptable.",
    definition: "Inflation as measured by the consumer price index (CPI) reflects the annual percentage change in the cost to the average consumer of acquiring a basket of goods and services.",
    methodology: "CPI tracks consumer prices in each country. World Bank and IMF figures may differ due to different base years and coverage.",
  },
  {
    slug: "government-debt",
    name: "Government Debt (% of GDP)",
    category: "Economy",
    worldBankCode: "GC.DOD.TOTL.GD.ZS",
    imfCode: "GGXWDG_NGDP",
    unit: "% of GDP",
    displayUnit: "%",
    polarity: "NEGATIVE",
    polarityRationale: "Very high government debt can crowd out private investment and increase vulnerability to fiscal crises, though context matters.",
    definition: "Central government debt, total, as a percentage of GDP. Includes domestic and external debt instruments.",
    methodology: "World Bank uses IMF Government Finance Statistics. IMF WEO uses gross general government debt. Definitions may differ by country.",
  },
  {
    slug: "exports-pct-gdp",
    name: "Exports of Goods & Services (% of GDP)",
    category: "Economy",
    worldBankCode: "NE.EXP.GNFS.ZS",
    imfCode: null,
    unit: "% of GDP",
    displayUnit: "%",
    polarity: "NEUTRAL",
    polarityRationale: "Export share reflects trade openness; very high export dependence can indicate vulnerability to external shocks.",
    definition: "Exports of goods and services represent the value of all goods and services provided to the rest of the world, as a share of GDP.",
    methodology: "Based on national accounts data. Includes merchandise and service exports.",
  },
  {
    slug: "imports-pct-gdp",
    name: "Imports of Goods & Services (% of GDP)",
    category: "Economy",
    worldBankCode: "NE.IMP.GNFS.ZS",
    imfCode: null,
    unit: "% of GDP",
    displayUnit: "%",
    polarity: "NEUTRAL",
    polarityRationale: "Import share reflects demand for foreign goods; context determines whether high imports are a sign of prosperity or trade imbalance.",
    definition: "Imports of goods and services represent the value of all goods and services received from the rest of the world, as a share of GDP.",
    methodology: "Based on national accounts data from World Bank.",
  },
  // ── POVERTY & INEQUALITY ──────────────────────────────────────────────────
  {
    slug: "poverty-215-day",
    name: "Poverty Headcount ($2.15/day)",
    category: "Poverty & Inequality",
    worldBankCode: "SI.POV.DDAY",
    imfCode: null,
    unit: "% of population",
    displayUnit: "%",
    polarity: "NEGATIVE",
    polarityRationale: "Higher poverty rate means a larger share of the population lives in extreme deprivation.",
    definition: "Percentage of the population living on less than $2.15 a day at 2017 international prices (PPP). This is the World Bank's international extreme poverty line.",
    methodology: "Based on household surveys harmonised by the World Bank Poverty and Inequality Platform (PIP). Coverage and survey years vary by country.",
  },
  {
    slug: "poverty-national",
    name: "Poverty Headcount (National Line)",
    category: "Poverty & Inequality",
    worldBankCode: "SI.POV.NAHC",
    imfCode: null,
    unit: "% of population",
    displayUnit: "%",
    polarity: "NEGATIVE",
    polarityRationale: "National poverty rates reflect country-specific definitions of minimum acceptable living standards.",
    definition: "Percentage of the population living below each country's own national poverty line. Lines vary significantly across countries and are not directly comparable.",
    methodology: "From national household surveys; definitions set by each country's statistical office.",
  },
  {
    slug: "gini-index",
    name: "Gini Index",
    category: "Poverty & Inequality",
    worldBankCode: "SI.POV.GINI",
    imfCode: null,
    unit: "Index (0–100)",
    displayUnit: "Gini",
    polarity: "NEGATIVE",
    polarityRationale: "Higher Gini = greater inequality in income distribution. 0 = perfect equality; 100 = one person has everything.",
    definition: "The Gini index measures the extent to which the distribution of income among individuals or households deviates from a perfectly equal distribution. 0 = perfect equality; 100 = perfect inequality.",
    methodology: "Calculated from household survey microdata. Survey coverage, years, and definitions vary. Not all countries have recent surveys.",
  },
  {
    slug: "income-share-top10",
    name: "Income Share — Top 10%",
    category: "Poverty & Inequality",
    worldBankCode: "SI.DST.10TH.10",
    imfCode: null,
    unit: "% of income",
    displayUnit: "%",
    polarity: "NEGATIVE",
    polarityRationale: "Higher share for the top 10% indicates greater concentration of income at the top.",
    definition: "Percentage of total income received by the richest 10% of the population.",
    methodology: "Based on household surveys from the World Bank PIP. Comparability across countries is limited by differing survey methods.",
  },
  {
    slug: "income-share-bottom10",
    name: "Income Share — Bottom 10%",
    category: "Poverty & Inequality",
    worldBankCode: "SI.DST.FRST.10",
    imfCode: null,
    unit: "% of income",
    displayUnit: "%",
    polarity: "POSITIVE",
    polarityRationale: "Higher share for the bottom 10% indicates more equitable income distribution.",
    definition: "Percentage of total income received by the poorest 10% of the population.",
    methodology: "Based on household surveys from the World Bank PIP.",
  },
  // ── HEALTH ────────────────────────────────────────────────────────────────
  {
    slug: "life-expectancy",
    name: "Life Expectancy at Birth",
    category: "Health",
    worldBankCode: "SP.DYN.LE00.IN",
    imfCode: null,
    unit: "Years",
    displayUnit: "yrs",
    polarity: "POSITIVE",
    polarityRationale: "Higher life expectancy generally indicates better health systems, nutrition, and living conditions.",
    definition: "The number of years a newborn is expected to live if current mortality patterns remain constant throughout their life. Combines male and female averages.",
    methodology: "Derived from age-specific death rates compiled from civil registration systems or sample registration surveys.",
  },
  {
    slug: "infant-mortality",
    name: "Infant Mortality Rate",
    category: "Health",
    worldBankCode: "SP.DYN.IMRT.IN",
    imfCode: null,
    unit: "Per 1,000 live births",
    displayUnit: "per 1k",
    polarity: "NEGATIVE",
    polarityRationale: "Higher infant mortality indicates greater risk of death in the first year of life, often reflecting inadequate healthcare and nutrition.",
    definition: "The number of infants dying before reaching one year of age, per 1,000 live births in a given year.",
    methodology: "From UN Inter-agency Group for Child Mortality Estimation (IGME). Uses model-based estimates where vital registration is incomplete.",
  },
  {
    slug: "maternal-mortality",
    name: "Maternal Mortality Ratio",
    category: "Health",
    worldBankCode: "SH.STA.MMRT",
    imfCode: null,
    unit: "Per 100,000 live births",
    displayUnit: "per 100k",
    polarity: "NEGATIVE",
    polarityRationale: "Higher maternal mortality indicates greater risk of death during pregnancy or childbirth, often reflecting healthcare system quality.",
    definition: "Number of women who die during pregnancy and childbirth per 100,000 live births. Includes deaths within 42 days of termination of pregnancy.",
    methodology: "WHO/UNICEF/UNFPA/World Bank joint estimates using a model-based approach. Actual data coverage is limited in many countries.",
  },
  {
    slug: "health-expenditure",
    name: "Current Health Expenditure (% of GDP)",
    category: "Health",
    worldBankCode: "SH.XPD.CHEX.GD.ZS",
    imfCode: null,
    unit: "% of GDP",
    displayUnit: "%",
    polarity: "NEUTRAL",
    polarityRationale: "Higher health spending may improve outcomes but does not guarantee them; efficiency matters as much as level.",
    definition: "Level of current health expenditure expressed as a percentage of GDP. Includes government, out-of-pocket, and private health spending. Excludes capital expenditure.",
    methodology: "WHO Global Health Expenditure Database, compiled from national health accounts and cross-validated with national surveys.",
  },
  // ── EDUCATION ─────────────────────────────────────────────────────────────
  {
    slug: "literacy-rate",
    name: "Literacy Rate (Adult)",
    category: "Education",
    worldBankCode: "SE.ADT.LITR.ZS",
    imfCode: null,
    unit: "% of adults 15+",
    displayUnit: "%",
    polarity: "POSITIVE",
    polarityRationale: "Higher adult literacy enables economic participation and is a fundamental human capability.",
    definition: "Percentage of people ages 15 and above who can read and write a short, simple statement about everyday life. Note: definition and survey methodology vary across countries.",
    methodology: "From UNESCO Institute for Statistics. Coverage is limited; many high-income countries do not report as near-universal literacy is assumed.",
  },
  {
    slug: "education-expenditure",
    name: "Government Expenditure on Education (% of GDP)",
    category: "Education",
    worldBankCode: "SE.XPD.TOTL.GD.ZS",
    imfCode: null,
    unit: "% of GDP",
    displayUnit: "%",
    polarity: "NEUTRAL",
    polarityRationale: "Higher education spending may improve outcomes but does not guarantee quality; efficiency and equity of spending matter.",
    definition: "General government expenditure on education (current, capital, and transfers), expressed as a percentage of GDP.",
    methodology: "UNESCO Institute for Statistics. Includes public expenditure only; private spending excluded.",
  },
  {
    slug: "primary-enrollment",
    name: "Primary School Enrollment (Gross %)",
    category: "Education",
    worldBankCode: "SE.PRM.ENRR",
    imfCode: null,
    unit: "% of relevant age group",
    displayUnit: "%",
    polarity: "POSITIVE",
    polarityRationale: "Higher enrollment indicates greater access to basic education. Can exceed 100% due to over-age and under-age students.",
    definition: "Gross enrollment ratio is the ratio of total enrollment, regardless of age, to the population of the age group that officially corresponds to the level of education shown.",
    methodology: "UNESCO Institute for Statistics. Gross ratios can exceed 100% because of grade repetition and early/late entry.",
  },
  {
    slug: "secondary-enrollment",
    name: "Secondary School Enrollment (Gross %)",
    category: "Education",
    worldBankCode: "SE.SEC.ENRR",
    imfCode: null,
    unit: "% of relevant age group",
    displayUnit: "%",
    polarity: "POSITIVE",
    polarityRationale: "Higher secondary enrollment indicates greater access to secondary education, which significantly affects future economic outcomes.",
    definition: "Gross secondary school enrollment ratio — total enrollment regardless of age, expressed as a percentage of the eligible official secondary age group.",
    methodology: "UNESCO Institute for Statistics.",
  },
  // ── EMPLOYMENT ────────────────────────────────────────────────────────────
  {
    slug: "unemployment",
    name: "Unemployment Rate",
    category: "Employment",
    worldBankCode: "SL.UEM.TOTL.ZS",
    imfCode: null,
    unit: "% of labor force",
    displayUnit: "%",
    polarity: "NEGATIVE",
    polarityRationale: "Higher unemployment indicates a greater share of the workforce unable to find work.",
    definition: "Unemployment refers to the share of the labor force that is without work but available for and seeking employment. ILO modelled estimates.",
    methodology: "ILO modelled estimates harmonised across countries. Definitions and survey methods vary; some countries exclude certain categories of jobseekers.",
  },
  {
    slug: "labor-force-participation",
    name: "Labor Force Participation Rate",
    category: "Employment",
    worldBankCode: "SL.TLF.CACT.ZS",
    imfCode: null,
    unit: "% of working-age population",
    displayUnit: "%",
    polarity: "NEUTRAL",
    polarityRationale: "Higher participation can mean a productive workforce, but also may reflect necessity (e.g., lack of social safety nets) or exclude unpaid care work.",
    definition: "Proportion of the population ages 15–64 that is economically active: all people who supply labor for production of goods and services during a reference period.",
    methodology: "ILO modelled estimates. Includes employed and unemployed people; excludes discouraged workers in some definitions.",
  },
  // ── POPULATION ────────────────────────────────────────────────────────────
  {
    slug: "population-total",
    name: "Population, Total",
    category: "Population",
    worldBankCode: "SP.POP.TOTL",
    imfCode: null,
    unit: "People",
    displayUnit: "people",
    polarity: "NEUTRAL",
    polarityRationale: "Population size is neither inherently good nor bad; context determines significance.",
    definition: "Total population based on the de facto definition of population, which counts all residents regardless of legal status or citizenship.",
    methodology: "World Bank estimates based on national statistical systems and UN DESA estimates.",
  },
  {
    slug: "population-growth",
    name: "Population Growth (Annual %)",
    category: "Population",
    worldBankCode: "SP.POP.GROW",
    imfCode: null,
    unit: "% per year",
    displayUnit: "%",
    polarity: "NEUTRAL",
    polarityRationale: "Neither high nor low growth is inherently good or bad; depends on economic context, resource availability, and demographic structure.",
    definition: "Annual population growth rate for year t is the exponential rate of growth of midyear population from year t-1 to t.",
    methodology: "Based on World Bank population data derived from national statistical offices and UN DESA.",
  },
  {
    slug: "population-65plus",
    name: "Population Ages 65+ (% of Total)",
    category: "Population",
    worldBankCode: "SP.POP.65UP.TO.ZS",
    imfCode: null,
    unit: "% of population",
    displayUnit: "%",
    polarity: "NEUTRAL",
    polarityRationale: "Higher elderly share may indicate longer life expectancy (positive) but also greater dependency ratio pressures on pension systems.",
    definition: "Population ages 65 and above as a percentage of total population.",
    methodology: "Based on World Bank population data and UN DESA population projections.",
  },
  {
    slug: "population-0-14",
    name: "Population Ages 0–14 (% of Total)",
    category: "Population",
    worldBankCode: "SP.POP.0014.TO.ZS",
    imfCode: null,
    unit: "% of population",
    displayUnit: "%",
    polarity: "NEUTRAL",
    polarityRationale: "High youth share may indicate future workforce growth (positive) or high dependency ratio (pressure on education spending).",
    definition: "Population between the ages 0 to 14 as a percentage of total population.",
    methodology: "Based on World Bank and UN DESA population data.",
  },
  {
    slug: "net-migration",
    name: "Net Migration",
    category: "Population",
    worldBankCode: "SM.POP.NETM",
    imfCode: null,
    unit: "People (5-year total)",
    displayUnit: "people",
    polarity: "NEUTRAL",
    polarityRationale: "Positive net migration = more immigrants than emigrants. Neither positive nor negative is inherently good or bad; context determines significance.",
    definition: "Net number of migrants during a five-year period. Negative = more emigrants than immigrants.",
    methodology: "UN DESA estimates. Based on census data, population registers, and other sources. Five-year period averages, not annual.",
  },
  // ── RESOURCES & ENVIRONMENT ──────────────────────────────────────────────
  {
    slug: "natural-resource-rents",
    name: "Total Natural Resource Rents (% of GDP)",
    category: "Resources & Human Capital",
    worldBankCode: "NY.GDP.TOTL.RT.ZS",
    imfCode: null,
    unit: "% of GDP",
    displayUnit: "%",
    polarity: "NEUTRAL",
    polarityRationale: "High resource rents can fuel growth but also create 'resource curse' dynamics. Neither inherently positive nor negative.",
    definition: "The sum of oil rents, natural gas rents, coal rents, mineral rents, and forest rents as a share of GDP.",
    methodology: "Calculated by World Bank as the difference between the price of a commodity and the average cost of producing it, multiplied by the quantity extracted.",
  },
  {
    slug: "oil-rents",
    name: "Oil Rents (% of GDP)",
    category: "Resources & Human Capital",
    worldBankCode: "NY.GDP.PETR.RT.ZS",
    imfCode: null,
    unit: "% of GDP",
    displayUnit: "%",
    polarity: "NEUTRAL",
    polarityRationale: "Oil rents reflect the economic value of oil extraction; high dependence can create boom-bust cycles.",
    definition: "Oil rents are the difference between the value of crude oil production at world prices and total costs of production.",
    methodology: "World Bank. Uses global commodity price data and country-specific cost estimates.",
  },
  {
    slug: "mineral-rents",
    name: "Mineral Rents (% of GDP)",
    category: "Resources & Human Capital",
    worldBankCode: "NY.GDP.MINR.RT.ZS",
    imfCode: null,
    unit: "% of GDP",
    displayUnit: "%",
    polarity: "NEUTRAL",
    polarityRationale: "Mineral rents reflect economic value of mining activity relative to the economy.",
    definition: "Mineral rents are the difference between the value of production for a stock of minerals at world prices and their total costs of production.",
    methodology: "World Bank. Includes tin, gold, lead, zinc, iron, copper, nickel, silver, bauxite, and phosphate.",
  },
  {
    slug: "gas-rents",
    name: "Natural Gas Rents (% of GDP)",
    category: "Resources & Human Capital",
    worldBankCode: "NY.GDP.NGAS.RT.ZS",
    imfCode: null,
    unit: "% of GDP",
    displayUnit: "%",
    polarity: "NEUTRAL",
    polarityRationale: "Natural gas rents reflect economic value of gas extraction.",
    definition: "Natural gas rents are the difference between the value of natural gas production at world prices and total costs of production.",
    methodology: "World Bank. Uses global gas price data and country-specific cost estimates.",
  },
  {
    slug: "fuel-exports",
    name: "Fuel Exports (% of Merchandise Exports)",
    category: "Resources & Human Capital",
    worldBankCode: "TX.VAL.FUEL.ZS.UN",
    imfCode: null,
    unit: "% of merchandise exports",
    displayUnit: "%",
    polarity: "NEUTRAL",
    polarityRationale: "High fuel export share indicates resource export dependence, which carries both opportunities and vulnerability.",
    definition: "Fuel exports, as a share of all merchandise exports. Fuels include petroleum, petroleum products, natural gas, coal, and related materials.",
    methodology: "UN COMTRADE via World Bank.",
  },
  {
    slug: "ores-metal-exports",
    name: "Ores & Metals Exports (% of Merchandise Exports)",
    category: "Resources & Human Capital",
    worldBankCode: "TX.VAL.MMTL.ZS.UN",
    imfCode: null,
    unit: "% of merchandise exports",
    displayUnit: "%",
    polarity: "NEUTRAL",
    polarityRationale: "High ores/metals export share indicates resource extraction dependence.",
    definition: "Ores and metals exports as a share of merchandise exports. Includes copper, iron ore, aluminum, gold, and other metals.",
    methodology: "UN COMTRADE via World Bank.",
  },
  // ── INFRASTRUCTURE ────────────────────────────────────────────────────────
  {
    slug: "electricity-access",
    name: "Access to Electricity (% of Population)",
    category: "Infrastructure",
    worldBankCode: "EG.ELC.ACCS.ZS",
    imfCode: null,
    unit: "% of population",
    displayUnit: "%",
    polarity: "POSITIVE",
    polarityRationale: "Higher electricity access is a prerequisite for economic activity, education, and healthcare.",
    definition: "Percentage of the population with access to electricity.",
    methodology: "World Bank / IEA / ESMAP Tracking SDG7 report. Uses household surveys and administrative data.",
  },
  {
    slug: "internet-users",
    name: "Individuals Using the Internet (% of Population)",
    category: "Infrastructure",
    worldBankCode: "IT.NET.USER.ZS",
    imfCode: null,
    unit: "% of population",
    displayUnit: "%",
    polarity: "POSITIVE",
    polarityRationale: "Higher internet access enables economic participation, access to services, and information.",
    definition: "Internet users are individuals who have used the Internet (from any location) in the last 3 months.",
    methodology: "ITU/World Bank estimates from administrative data and household surveys.",
  },
  // ── LIVING STANDARDS & STRUCTURE ─────────────────────────────────────────
  {
    slug: "manufacturing-share",
    name: "Manufacturing, Value Added (% of GDP)",
    category: "Living Standards",
    worldBankCode: "NV.IND.MANF.ZS",
    imfCode: null,
    unit: "% of GDP",
    displayUnit: "%",
    polarity: "NEUTRAL",
    polarityRationale: "Manufacturing share reflects economic structure; neither high nor low is universally better.",
    definition: "Manufacturing refers to industries belonging to ISIC divisions 10–33. Value added is the net output of a sector after adding up all outputs and subtracting intermediate inputs.",
    methodology: "World Bank national accounts data. Manufacturing definition may vary slightly by country.",
  },
  {
    slug: "fdi-inflows",
    name: "FDI, Net Inflows (% of GDP)",
    category: "Economy",
    worldBankCode: "BX.KLT.DINV.WD.GD.ZS",
    imfCode: null,
    unit: "% of GDP",
    displayUnit: "%",
    polarity: "NEUTRAL",
    polarityRationale: "FDI inflows can bring capital, technology, and jobs, but very high FDI dependence can create vulnerabilities.",
    definition: "Foreign direct investment net inflows as a percentage of GDP. FDI is an investment made to acquire lasting interest in enterprises outside the investor's economy.",
    methodology: "IMF Balance of Payments statistics via World Bank.",
  },
  {
    slug: "tax-revenue",
    name: "Tax Revenue (% of GDP)",
    category: "Economy",
    worldBankCode: "GC.TAX.TOTL.GD.ZS",
    imfCode: null,
    unit: "% of GDP",
    displayUnit: "%",
    polarity: "NEUTRAL",
    polarityRationale: "Higher tax revenue can fund public services, but very high rates may reduce private investment. Context matters.",
    definition: "Tax revenue refers to compulsory transfers to the central government. Certain compulsory transfers such as fines, penalties, and most social security contributions are excluded.",
    methodology: "IMF Government Finance Statistics Yearbook and World Bank data.",
  },
  // ── MANUAL ONLY (no free API) ─────────────────────────────────────────────
  {
    slug: "wealth-per-adult",
    name: "Wealth per Adult (Median)",
    category: "Wealth",
    worldBankCode: null,
    imfCode: null,
    unit: "USD (2023)",
    displayUnit: "US$",
    polarity: "POSITIVE",
    polarityRationale: "Higher median wealth per adult indicates greater typical household wealth, not just average income.",
    definition: "Median net worth per adult including financial assets, real assets (mainly housing), and minus debts. Median is used rather than mean to reduce distortion from extreme top-end wealth.",
    methodology: "Credit Suisse Global Wealth Report / UBS (annual). Uses household survey data and statistical models. Classified as Estimated. No free machine-readable API exists.",
    isWealth: true,
  },
  {
    slug: "hdi",
    name: "Human Development Index (HDI)",
    category: "Resources & Human Capital",
    worldBankCode: null,
    imfCode: null,
    unit: "Index (0–1)",
    displayUnit: "HDI",
    polarity: "POSITIVE",
    polarityRationale: "Higher HDI indicates greater human development across health, education, and income dimensions.",
    definition: "The Human Development Index (HDI) is a composite statistic of life expectancy, education (mean and expected years of schooling), and per capita income indicators. Published by UNDP.",
    methodology: "UNDP Human Development Report Office. Combines normalized GNI per capita (PPP), life expectancy at birth, and education indices. Available from UNDP HDR open data.",
    isWealth: false,
  },
];

const CATEGORY_ORDER = [
  "Wealth", "Economy", "Poverty & Inequality", "Health",
  "Education", "Employment", "Population", "Living Standards",
  "Resources & Human Capital", "Infrastructure",
];

async function main() {
  console.log("🌱 ETW — Indicator Migration (add/update all 41 indicators)\n");

  // Ensure all categories exist
  const categoryMap = new Map<string, string>();
  for (let i = 0; i < CATEGORY_ORDER.length; i++) {
    const name = CATEGORY_ORDER[i];
    const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, "-");
    const cat = await prisma.category.upsert({
      where: { slug },
      create: { name, slug, displayOrder: i },
      update: { displayOrder: i },
    });
    categoryMap.set(name, cat.id);
    console.log(`  ✓ Category: ${name}`);
  }

  // Upsert each indicator
  let added = 0, updated = 0;
  for (let i = 0; i < INDICATORS.length; i++) {
    const ind = INDICATORS[i];
    const categoryId = categoryMap.get(ind.category);
    if (!categoryId) {
      console.error(`  ✗ Unknown category: ${ind.category} for ${ind.slug}`);
      continue;
    }

    await prisma.indicator.upsert({
      where: { slug: ind.slug },
      create: {
        slug: ind.slug,
        name: ind.name,
        categoryId,
        definition: ind.definition,
        methodology: ind.methodology ?? null,
        unit: ind.unit,
        displayUnit: ind.displayUnit ?? null,
        polarity: ind.polarity,
        polarityRationale: ind.polarityRationale ?? null,
        worldBankCode: ind.worldBankCode ?? null,
        imfCode: ind.imfCode ?? null,
        isWealth: ind.isWealth ?? false,
        displayOrder: i,
      },
      update: {
        name: ind.name,
        categoryId,
        definition: ind.definition,
        methodology: ind.methodology ?? null,
        unit: ind.unit,
        displayUnit: ind.displayUnit ?? null,
        polarity: ind.polarity,
        polarityRationale: ind.polarityRationale ?? null,
        worldBankCode: ind.worldBankCode ?? null,
        imfCode: ind.imfCode ?? null,
        isWealth: ind.isWealth ?? false,
        displayOrder: i,
      },
    });
    added++;
    console.log(`  ✓ ${ind.name} (${ind.worldBankCode ?? "manual only"})`);
  }

  console.log(`\n✅ Done: ${added} indicators upserted`);
  await prisma.$disconnect();
}

main().catch(e => {
  console.error(e);
  process.exit(1);
});
